sudo: required

language: go

services:
- docker

go:
  - "1.10.x"
  - master

script:
- make build

before_deploy:
- echo "$DOCKER_SECRET" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
- provider: script
  script: make build-image && make deploy-image
  skip_cleanup: true
  on:
    tags: true
    branch: master

notifications:
  email: false
